---
- name: basisconfiguratie
  hosts: AN-01
  gather_facts: false
  connection: local

  vars:
    cli:
      username: root
      password: cisco

  tasks:
    - name: global config settings
      ios_config:
        provider: "{{ cli }}"
        lines:
          - enable secret cisco
          - ipv6 unicast-routing
          - ip cef

    - name: line console password
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: line console 0
        lines:
          - login authentication default
          - password cisco

      register: print_output

    - name: line vty password
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: line vty 0 4
        lines:
          - login authentication default
          - password cisco

      register: print_output

    - name: line vty password
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: line vty 5 15
        lines:
          - login authentication default
          - password cisco

      register: print_output

    - name: banner motd
      ios_config:
        provider: "{{ cli }}"
        lines:
          - banner motd $ Niet toegankelijk $

      register: print_output

    - name: configure GigabitEthernet1/0 settings
      ios_config:
        lines:
          - description to AN-02
          - ip address 192.168.34.1 255.255.255.0
          - ipv6 address fdb0::1/13 eui-64
          - mpls ip
          - no shut
        parents: interface GigabitEthernet1/0

        host: "{{ ansible_host }}"
        username: root
        password: cisco

    - name: configure GigabitEthernet2/0 settings
      ios_config:
        lines:
          - description to AN-03
          - ip address 192.168.36.1 255.255.255.0
          - ipv6 address fdb8::1/13 eui-64
          - mpls ip
          - no shut
        parents: interface GigabitEthernet2/0

        host: "{{ ansible_host }}"
        username: root
        password: cisco

    - name: configure Loopback1 settings
      ios_config:
        lines:
          - description to Loopback
          - ip address 10.1.2.1 255.255.255.0
          - no shut
        parents: interface Loopback1

        host: "{{ ansible_host }}"
        username: root
        password: cisco

    - name: configure Serial4/0 settings
      ios_config:
        lines:
          - description to MA-01
          - ip address 10.10.10.22 255.255.255.252
          - no shut
        parents: interface Serial4/0

        host: "{{ ansible_host }}"
        username: root
        password: cisco

    - name: configure Serial4/1 settings
      ios_config:
        lines:
          - description to TY-01
          - ip address 10.10.10.18 255.255.255.252
          - no shut
        parents: interface Serial4/1

        host: "{{ ansible_host }}"
        username: root
        password: cisco

    - name: configure Serial4/2 settings
      ios_config:
        lines:
          - description to SV-01
          - ip address 10.10.10.10 255.255.255.252
          - no shut
        parents: interface Serial4/2

        host: "{{ ansible_host }}"
        username: root
        password: cisco

    - name: enable ospf
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: router ospf 1
        lines:
          - network 192.168.34.0 255.255.255.0 area 0
          - network 192.168.36.0 255.255.255.0 area 0
          - network 10.10.10.0 255.255.255.0 area 0

    - name: NAT inside
      ios_config:
        provider: "{{ cli }}"
        lines:
          - ip nat inside
        parents:
          - interface GigabitEthernet1/0
          - interface GigabitEthernet2/0

    - name: NAT outside
      ios_config:
        provider: "{{ cli }}"
        lines:
          - ip nat outside
        parents:
          - interface Serial4/1
          - interface Serial4/2
          - interface Serial4/3

    - name: ACL
      ios_config:
        authorize: yes
        lines:
          - access-list 1 permit 192.168.0.0 0.0.255.255
          - access-list 99 permit 10.10.10.0 0.0.0.255
          - access-list 99 deny any

    - name: NAT pool
      ios_config:
        authorize: yes
        lines:
          - ip nat pool POOL1 10.10.10.10 10.10.10.50 netmask 255.255.255.0
          - ip nat inside source list 1 pool POOL1

    - name: BGP
      ios_config:
        authorize: yes
        parents: router bgp 64512
        lines:
          - neighbor 10.10.10.17 remote-as 64521
          - neighbor 10.10.10.21 remote-as 64518
          - neighbor 10.10.10.9 remote-as 64515
          - network 10.1.2.0 mask 255.255.255.0
          - network 192.168.34.0 mask 255.255.255.0
          - network 192.168.36.0 mask 255.255.255.0

    - name: DHCP
      ios_config:
        provider: "{{ cli }}"
        parents: ip dhcp pool dhcp1
        lines:
          - network 192.168.34.0 255.255.255.0
          - default-router 192.168.34.1
          - dns-server 192.168.34.1
          - ip dhcp excluded-address 192.168.34.1 192.168.34.2

    - name: IP SLA AN
      ios_config:
        authorize: yes
        parents: ip sla 1001
        lines:
          - icmp-echo 10.10.10.17
          - frequency 30
        after: ip sla schedule 1001 life forever start-time now

    - name: save config
      ios_command:
        commands:
          - write memory

        host: "{{ ansible_host }}"
        username: root
        password: cisco
